version: "3"

vars:
  BINARY_NAME: api
  BUILD_DIR: ./build

tasks:
  build:
    desc: Build the API binary into ./build
    cmds:
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}}.exe ./cmd/server

  buildlinux:
    desc: Build the API binary into ./build for linux os
    cmds:
      - $env:GOOS="linux"
      - $env:GOARCH="amd64"
      - $env:CGO_ENABLED="0"
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} ./cmd/server
      - Remove-Item Env:\GOOS, Env:\GOARCH, Env:\CGO_ENABLED

  run:
    desc: Build and run the API
    deps: [build]
    cmds:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}.exe"

  clean:
    desc: Remove build artifacts
    cmds:
      - powershell -Command "Remove-Item -Recurse -Force {{.BUILD_DIR}} -ErrorAction SilentlyContinue"

  tidy:
    desc: Tidy go.mod / go.sum
    cmds:
      - go mod tidy

  test:
    desc: Run tests
    cmds:
      - go test ./...

  database:
    desc: open database
    cmds:
      - python -m pgcli postgres://qr_menu_owner:6wKkCaF3Td37he@alhaos.ru:5432/qr_menu?sslmode=disable
